### Application Level Image CI - Freescout
### Dave Conroy <tiredofit@github>

name: 'Multi PHP Version Build'
on:
  push:
    paths:
    - '**'
    - '!README.md'
jobs:
  php81:
    uses: tiredofit/github_actions/.github/workflows/php81_alpine_amd64_arm64.yml@main
    secrets: inherit
  php82:
    uses: tiredofit/github_actions/.github/workflows/php82_alpine_amd64_arm64.yml@main
    secrets: inherit
  php83:
    uses: tiredofit/github_actions/.github/workflows/php83_alpine_amd64_arm64.yml@main
    secrets: inherit
